spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ddok
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver